### ISSUE TITLE
Output Readability

### ISSUE THREAD

**Issue by spectrumvoip** [ZoiPer/provisioningexample#1]
Hi,

Since this is mostly a sample for documentation, it would be good to add:

```
            $xml->preserveWhiteSpace = false;
            $xml->formatOutput = true;
```

right before the echo statements.

This makes it so when folks View Source on the generated xml, it is formatted nicely instead of all on one unreadable line.

Thanks
Shanon

**Comment by Dyno1990** [comment]
Hi, 

Thank you for your suggestion. 
The provisioning example has been updated according to your proposal and was adjusted in a way where it should always show the tags on separate lines and the with the relevant indent based on the layer of the tag (the children and parents).
